// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package presentation

import (
	"context"
	"sync"

	domain "github.com/becosuke/guestbook/api/internal/domain/post"
)

// Ensure, that UsecaseMock does implement Usecase.
// If this is not the case, regenerate this file with moq.
var _ Usecase = &UsecaseMock{}

// UsecaseMock is a mock implementation of Usecase.
//
//	func TestSomethingThatUsesUsecase(t *testing.T) {
//
//		// make and configure a mocked Usecase
//		mockedUsecase := &UsecaseMock{
//			CreateFunc: func(contextMoqParam context.Context, post *domain.Post) (*domain.Post, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(contextMoqParam context.Context, postID *domain.PostID) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(contextMoqParam context.Context, postID *domain.PostID) (*domain.Post, error) {
//				panic("mock out the Get method")
//			},
//			RangeFunc: func(contextMoqParam context.Context, pageOption *domain.PageOption) ([]*domain.Post, error) {
//				panic("mock out the Range method")
//			},
//			UpdateFunc: func(contextMoqParam context.Context, post *domain.Post) (*domain.Post, error) {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedUsecase in code that requires Usecase
//		// and then make assertions.
//
//	}
type UsecaseMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(contextMoqParam context.Context, post *domain.Post) (*domain.Post, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(contextMoqParam context.Context, postID *domain.PostID) error

	// GetFunc mocks the Get method.
	GetFunc func(contextMoqParam context.Context, postID *domain.PostID) (*domain.Post, error)

	// RangeFunc mocks the Range method.
	RangeFunc func(contextMoqParam context.Context, pageOption *domain.PageOption) ([]*domain.Post, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(contextMoqParam context.Context, post *domain.Post) (*domain.Post, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Post is the post argument value.
			Post *domain.Post
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// PostID is the postID argument value.
			PostID *domain.PostID
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// PostID is the postID argument value.
			PostID *domain.PostID
		}
		// Range holds details about calls to the Range method.
		Range []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// PageOption is the pageOption argument value.
			PageOption *domain.PageOption
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Post is the post argument value.
			Post *domain.Post
		}
	}
	lockCreate sync.RWMutex
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockRange  sync.RWMutex
	lockUpdate sync.RWMutex
}

// Create calls CreateFunc.
func (mock *UsecaseMock) Create(contextMoqParam context.Context, post *domain.Post) (*domain.Post, error) {
	if mock.CreateFunc == nil {
		panic("UsecaseMock.CreateFunc: method is nil but Usecase.Create was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Post            *domain.Post
	}{
		ContextMoqParam: contextMoqParam,
		Post:            post,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(contextMoqParam, post)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedUsecase.CreateCalls())
func (mock *UsecaseMock) CreateCalls() []struct {
	ContextMoqParam context.Context
	Post            *domain.Post
} {
	var calls []struct {
		ContextMoqParam context.Context
		Post            *domain.Post
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *UsecaseMock) Delete(contextMoqParam context.Context, postID *domain.PostID) error {
	if mock.DeleteFunc == nil {
		panic("UsecaseMock.DeleteFunc: method is nil but Usecase.Delete was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		PostID          *domain.PostID
	}{
		ContextMoqParam: contextMoqParam,
		PostID:          postID,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(contextMoqParam, postID)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedUsecase.DeleteCalls())
func (mock *UsecaseMock) DeleteCalls() []struct {
	ContextMoqParam context.Context
	PostID          *domain.PostID
} {
	var calls []struct {
		ContextMoqParam context.Context
		PostID          *domain.PostID
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *UsecaseMock) Get(contextMoqParam context.Context, postID *domain.PostID) (*domain.Post, error) {
	if mock.GetFunc == nil {
		panic("UsecaseMock.GetFunc: method is nil but Usecase.Get was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		PostID          *domain.PostID
	}{
		ContextMoqParam: contextMoqParam,
		PostID:          postID,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(contextMoqParam, postID)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedUsecase.GetCalls())
func (mock *UsecaseMock) GetCalls() []struct {
	ContextMoqParam context.Context
	PostID          *domain.PostID
} {
	var calls []struct {
		ContextMoqParam context.Context
		PostID          *domain.PostID
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Range calls RangeFunc.
func (mock *UsecaseMock) Range(contextMoqParam context.Context, pageOption *domain.PageOption) ([]*domain.Post, error) {
	if mock.RangeFunc == nil {
		panic("UsecaseMock.RangeFunc: method is nil but Usecase.Range was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		PageOption      *domain.PageOption
	}{
		ContextMoqParam: contextMoqParam,
		PageOption:      pageOption,
	}
	mock.lockRange.Lock()
	mock.calls.Range = append(mock.calls.Range, callInfo)
	mock.lockRange.Unlock()
	return mock.RangeFunc(contextMoqParam, pageOption)
}

// RangeCalls gets all the calls that were made to Range.
// Check the length with:
//
//	len(mockedUsecase.RangeCalls())
func (mock *UsecaseMock) RangeCalls() []struct {
	ContextMoqParam context.Context
	PageOption      *domain.PageOption
} {
	var calls []struct {
		ContextMoqParam context.Context
		PageOption      *domain.PageOption
	}
	mock.lockRange.RLock()
	calls = mock.calls.Range
	mock.lockRange.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *UsecaseMock) Update(contextMoqParam context.Context, post *domain.Post) (*domain.Post, error) {
	if mock.UpdateFunc == nil {
		panic("UsecaseMock.UpdateFunc: method is nil but Usecase.Update was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Post            *domain.Post
	}{
		ContextMoqParam: contextMoqParam,
		Post:            post,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(contextMoqParam, post)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedUsecase.UpdateCalls())
func (mock *UsecaseMock) UpdateCalls() []struct {
	ContextMoqParam context.Context
	Post            *domain.Post
} {
	var calls []struct {
		ContextMoqParam context.Context
		Post            *domain.Post
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
