// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package interfaces

import (
	"context"
	"sync"

	"github.com/becosuke/guestbook/api/internal/domain/entity"
)

// Ensure, that CommanderMock does implement Commander.
// If this is not the case, regenerate this file with moq.
var _ Commander = &CommanderMock{}

// CommanderMock is a mock implementation of Commander.
//
//	func TestSomethingThatUsesCommander(t *testing.T) {
//
//		// make and configure a mocked Commander
//		mockedCommander := &CommanderMock{
//			CreateFunc: func(contextMoqParam context.Context, post *entity.Post) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(contextMoqParam context.Context, postID *entity.PostID) error {
//				panic("mock out the Delete method")
//			},
//			UpdateFunc: func(contextMoqParam context.Context, post *entity.Post) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedCommander in code that requires Commander
//		// and then make assertions.
//
//	}
type CommanderMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(contextMoqParam context.Context, post *entity.Post) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(contextMoqParam context.Context, postID *entity.PostID) error

	// UpdateFunc mocks the Update method.
	UpdateFunc func(contextMoqParam context.Context, post *entity.Post) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Post is the post argument value.
			Post *entity.Post
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// PostID is the postID argument value.
			PostID *entity.PostID
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Post is the post argument value.
			Post *entity.Post
		}
	}
	lockCreate sync.RWMutex
	lockDelete sync.RWMutex
	lockUpdate sync.RWMutex
}

// Create calls CreateFunc.
func (mock *CommanderMock) Create(contextMoqParam context.Context, post *entity.Post) error {
	if mock.CreateFunc == nil {
		panic("CommanderMock.CreateFunc: method is nil but Commander.Create was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Post            *entity.Post
	}{
		ContextMoqParam: contextMoqParam,
		Post:            post,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(contextMoqParam, post)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedCommander.CreateCalls())
func (mock *CommanderMock) CreateCalls() []struct {
	ContextMoqParam context.Context
	Post            *entity.Post
} {
	var calls []struct {
		ContextMoqParam context.Context
		Post            *entity.Post
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *CommanderMock) Delete(contextMoqParam context.Context, postID *entity.PostID) error {
	if mock.DeleteFunc == nil {
		panic("CommanderMock.DeleteFunc: method is nil but Commander.Delete was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		PostID          *entity.PostID
	}{
		ContextMoqParam: contextMoqParam,
		PostID:          postID,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(contextMoqParam, postID)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedCommander.DeleteCalls())
func (mock *CommanderMock) DeleteCalls() []struct {
	ContextMoqParam context.Context
	PostID          *entity.PostID
} {
	var calls []struct {
		ContextMoqParam context.Context
		PostID          *entity.PostID
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *CommanderMock) Update(contextMoqParam context.Context, post *entity.Post) error {
	if mock.UpdateFunc == nil {
		panic("CommanderMock.UpdateFunc: method is nil but Commander.Update was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Post            *entity.Post
	}{
		ContextMoqParam: contextMoqParam,
		Post:            post,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(contextMoqParam, post)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedCommander.UpdateCalls())
func (mock *CommanderMock) UpdateCalls() []struct {
	ContextMoqParam context.Context
	Post            *entity.Post
} {
	var calls []struct {
		ContextMoqParam context.Context
		Post            *entity.Post
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
