// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package interfaces

import (
	"context"
	"github.com/becosuke/guestbook/api/internal/domain"
	"sync"
)

// Ensure, that PaginatorMock does implement Paginator.
// If this is not the case, regenerate this file with moq.
var _ Paginator = &PaginatorMock{}

// PaginatorMock is a mock implementation of Paginator.
//
//	func TestSomethingThatUsesPaginator(t *testing.T) {
//
//		// make and configure a mocked Paginator
//		mockedPaginator := &PaginatorMock{
//			GetPaginationFunc: func(contextMoqParam context.Context, paginationID *domain.PaginationID) (*domain.Pagination, error) {
//				panic("mock out the GetPagination method")
//			},
//			SavePaginationFunc: func(contextMoqParam context.Context, pagination *domain.Pagination) error {
//				panic("mock out the SavePagination method")
//			},
//		}
//
//		// use mockedPaginator in code that requires Paginator
//		// and then make assertions.
//
//	}
type PaginatorMock struct {
	// GetPaginationFunc mocks the GetPagination method.
	GetPaginationFunc func(contextMoqParam context.Context, paginationID *domain.PaginationID) (*domain.Pagination, error)

	// SavePaginationFunc mocks the SavePagination method.
	SavePaginationFunc func(contextMoqParam context.Context, pagination *domain.Pagination) error

	// calls tracks calls to the methods.
	calls struct {
		// GetPagination holds details about calls to the GetPagination method.
		GetPagination []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// PaginationID is the paginationID argument value.
			PaginationID *domain.PaginationID
		}
		// SavePagination holds details about calls to the SavePagination method.
		SavePagination []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Pagination is the pagination argument value.
			Pagination *domain.Pagination
		}
	}
	lockGetPagination  sync.RWMutex
	lockSavePagination sync.RWMutex
}

// GetPagination calls GetPaginationFunc.
func (mock *PaginatorMock) GetPagination(contextMoqParam context.Context, paginationID *domain.PaginationID) (*domain.Pagination, error) {
	if mock.GetPaginationFunc == nil {
		panic("PaginatorMock.GetPaginationFunc: method is nil but Paginator.GetPagination was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		PaginationID    *domain.PaginationID
	}{
		ContextMoqParam: contextMoqParam,
		PaginationID:    paginationID,
	}
	mock.lockGetPagination.Lock()
	mock.calls.GetPagination = append(mock.calls.GetPagination, callInfo)
	mock.lockGetPagination.Unlock()
	return mock.GetPaginationFunc(contextMoqParam, paginationID)
}

// GetPaginationCalls gets all the calls that were made to GetPagination.
// Check the length with:
//
//	len(mockedPaginator.GetPaginationCalls())
func (mock *PaginatorMock) GetPaginationCalls() []struct {
	ContextMoqParam context.Context
	PaginationID    *domain.PaginationID
} {
	var calls []struct {
		ContextMoqParam context.Context
		PaginationID    *domain.PaginationID
	}
	mock.lockGetPagination.RLock()
	calls = mock.calls.GetPagination
	mock.lockGetPagination.RUnlock()
	return calls
}

// SavePagination calls SavePaginationFunc.
func (mock *PaginatorMock) SavePagination(contextMoqParam context.Context, pagination *domain.Pagination) error {
	if mock.SavePaginationFunc == nil {
		panic("PaginatorMock.SavePaginationFunc: method is nil but Paginator.SavePagination was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Pagination      *domain.Pagination
	}{
		ContextMoqParam: contextMoqParam,
		Pagination:      pagination,
	}
	mock.lockSavePagination.Lock()
	mock.calls.SavePagination = append(mock.calls.SavePagination, callInfo)
	mock.lockSavePagination.Unlock()
	return mock.SavePaginationFunc(contextMoqParam, pagination)
}

// SavePaginationCalls gets all the calls that were made to SavePagination.
// Check the length with:
//
//	len(mockedPaginator.SavePaginationCalls())
func (mock *PaginatorMock) SavePaginationCalls() []struct {
	ContextMoqParam context.Context
	Pagination      *domain.Pagination
} {
	var calls []struct {
		ContextMoqParam context.Context
		Pagination      *domain.Pagination
	}
	mock.lockSavePagination.RLock()
	calls = mock.calls.SavePagination
	mock.lockSavePagination.RUnlock()
	return calls
}
