// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package interfaces

import (
	"context"
	"github.com/becosuke/guestbook/api/internal/domain"
	"sync"
)

// Ensure, that PaginatorMock does implement Paginator.
// If this is not the case, regenerate this file with moq.
var _ Paginator = &PaginatorMock{}

// PaginatorMock is a mock implementation of Paginator.
//
//	func TestSomethingThatUsesPaginator(t *testing.T) {
//
//		// make and configure a mocked Paginator
//		mockedPaginator := &PaginatorMock{
//			GetFunc: func(contextMoqParam context.Context, paginationID *domain.PaginationID) (*domain.Pagination, error) {
//				panic("mock out the Get method")
//			},
//			SaveFunc: func(contextMoqParam context.Context, pagination *domain.Pagination) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedPaginator in code that requires Paginator
//		// and then make assertions.
//
//	}
type PaginatorMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(contextMoqParam context.Context, paginationID *domain.PaginationID) (*domain.Pagination, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(contextMoqParam context.Context, pagination *domain.Pagination) error

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// PaginationID is the paginationID argument value.
			PaginationID *domain.PaginationID
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Pagination is the pagination argument value.
			Pagination *domain.Pagination
		}
	}
	lockGet  sync.RWMutex
	lockSave sync.RWMutex
}

// Get calls GetFunc.
func (mock *PaginatorMock) Get(contextMoqParam context.Context, paginationID *domain.PaginationID) (*domain.Pagination, error) {
	if mock.GetFunc == nil {
		panic("PaginatorMock.GetFunc: method is nil but Paginator.Get was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		PaginationID    *domain.PaginationID
	}{
		ContextMoqParam: contextMoqParam,
		PaginationID:    paginationID,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(contextMoqParam, paginationID)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedPaginator.GetCalls())
func (mock *PaginatorMock) GetCalls() []struct {
	ContextMoqParam context.Context
	PaginationID    *domain.PaginationID
} {
	var calls []struct {
		ContextMoqParam context.Context
		PaginationID    *domain.PaginationID
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *PaginatorMock) Save(contextMoqParam context.Context, pagination *domain.Pagination) error {
	if mock.SaveFunc == nil {
		panic("PaginatorMock.SaveFunc: method is nil but Paginator.Save was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Pagination      *domain.Pagination
	}{
		ContextMoqParam: contextMoqParam,
		Pagination:      pagination,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(contextMoqParam, pagination)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedPaginator.SaveCalls())
func (mock *PaginatorMock) SaveCalls() []struct {
	ContextMoqParam context.Context
	Pagination      *domain.Pagination
} {
	var calls []struct {
		ContextMoqParam context.Context
		Pagination      *domain.Pagination
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}
