// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package interfaces

import (
	"context"
	"github.com/becosuke/guestbook/api/internal/domain"
	"sync"
)

// Ensure, that PostQuerierMock does implement PostQuerier.
// If this is not the case, regenerate this file with moq.
var _ PostQuerier = &PostQuerierMock{}

// PostQuerierMock is a mock implementation of PostQuerier.
//
//	func TestSomethingThatUsesPostQuerier(t *testing.T) {
//
//		// make and configure a mocked PostQuerier
//		mockedPostQuerier := &PostQuerierMock{
//			GetFunc: func(contextMoqParam context.Context, postID *domain.PostID) (*domain.Post, error) {
//				panic("mock out the Get method")
//			},
//			RangeFunc: func(ctx context.Context, pageSize int32, cursor *domain.PostCursor) ([]*domain.Post, error) {
//				panic("mock out the Range method")
//			},
//		}
//
//		// use mockedPostQuerier in code that requires PostQuerier
//		// and then make assertions.
//
//	}
type PostQuerierMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(contextMoqParam context.Context, postID *domain.PostID) (*domain.Post, error)

	// RangeFunc mocks the Range method.
	RangeFunc func(ctx context.Context, pageSize int32, cursor *domain.PostCursor) ([]*domain.Post, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// PostID is the postID argument value.
			PostID *domain.PostID
		}
		// Range holds details about calls to the Range method.
		Range []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PageSize is the pageSize argument value.
			PageSize int32
			// Cursor is the cursor argument value.
			Cursor *domain.PostCursor
		}
	}
	lockGet   sync.RWMutex
	lockRange sync.RWMutex
}

// Get calls GetFunc.
func (mock *PostQuerierMock) Get(contextMoqParam context.Context, postID *domain.PostID) (*domain.Post, error) {
	if mock.GetFunc == nil {
		panic("PostQuerierMock.GetFunc: method is nil but PostQuerier.Get was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		PostID          *domain.PostID
	}{
		ContextMoqParam: contextMoqParam,
		PostID:          postID,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(contextMoqParam, postID)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedPostQuerier.GetCalls())
func (mock *PostQuerierMock) GetCalls() []struct {
	ContextMoqParam context.Context
	PostID          *domain.PostID
} {
	var calls []struct {
		ContextMoqParam context.Context
		PostID          *domain.PostID
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Range calls RangeFunc.
func (mock *PostQuerierMock) Range(ctx context.Context, pageSize int32, cursor *domain.PostCursor) ([]*domain.Post, error) {
	if mock.RangeFunc == nil {
		panic("PostQuerierMock.RangeFunc: method is nil but PostQuerier.Range was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		PageSize int32
		Cursor   *domain.PostCursor
	}{
		Ctx:      ctx,
		PageSize: pageSize,
		Cursor:   cursor,
	}
	mock.lockRange.Lock()
	mock.calls.Range = append(mock.calls.Range, callInfo)
	mock.lockRange.Unlock()
	return mock.RangeFunc(ctx, pageSize, cursor)
}

// RangeCalls gets all the calls that were made to Range.
// Check the length with:
//
//	len(mockedPostQuerier.RangeCalls())
func (mock *PostQuerierMock) RangeCalls() []struct {
	Ctx      context.Context
	PageSize int32
	Cursor   *domain.PostCursor
} {
	var calls []struct {
		Ctx      context.Context
		PageSize int32
		Cursor   *domain.PostCursor
	}
	mock.lockRange.RLock()
	calls = mock.calls.Range
	mock.lockRange.RUnlock()
	return calls
}
