// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package interfaces

import (
	"context"
	"github.com/becosuke/guestbook/api/internal/domain"
	"sync"
)

// Ensure, that PostCommanderMock does implement PostCommander.
// If this is not the case, regenerate this file with moq.
var _ PostCommander = &PostCommanderMock{}

// PostCommanderMock is a mock implementation of PostCommander.
//
//	func TestSomethingThatUsesPostCommander(t *testing.T) {
//
//		// make and configure a mocked PostCommander
//		mockedPostCommander := &PostCommanderMock{
//			CreatePostFunc: func(contextMoqParam context.Context, post *domain.Post) error {
//				panic("mock out the CreatePost method")
//			},
//			DeletePostFunc: func(contextMoqParam context.Context, postID *domain.PostID) error {
//				panic("mock out the DeletePost method")
//			},
//			UpdatePostFunc: func(contextMoqParam context.Context, post *domain.Post) error {
//				panic("mock out the UpdatePost method")
//			},
//		}
//
//		// use mockedPostCommander in code that requires PostCommander
//		// and then make assertions.
//
//	}
type PostCommanderMock struct {
	// CreatePostFunc mocks the CreatePost method.
	CreatePostFunc func(contextMoqParam context.Context, post *domain.Post) error

	// DeletePostFunc mocks the DeletePost method.
	DeletePostFunc func(contextMoqParam context.Context, postID *domain.PostID) error

	// UpdatePostFunc mocks the UpdatePost method.
	UpdatePostFunc func(contextMoqParam context.Context, post *domain.Post) error

	// calls tracks calls to the methods.
	calls struct {
		// CreatePost holds details about calls to the CreatePost method.
		CreatePost []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Post is the post argument value.
			Post *domain.Post
		}
		// DeletePost holds details about calls to the DeletePost method.
		DeletePost []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// PostID is the postID argument value.
			PostID *domain.PostID
		}
		// UpdatePost holds details about calls to the UpdatePost method.
		UpdatePost []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Post is the post argument value.
			Post *domain.Post
		}
	}
	lockCreatePost sync.RWMutex
	lockDeletePost sync.RWMutex
	lockUpdatePost sync.RWMutex
}

// CreatePost calls CreatePostFunc.
func (mock *PostCommanderMock) CreatePost(contextMoqParam context.Context, post *domain.Post) error {
	if mock.CreatePostFunc == nil {
		panic("PostCommanderMock.CreatePostFunc: method is nil but PostCommander.CreatePost was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Post            *domain.Post
	}{
		ContextMoqParam: contextMoqParam,
		Post:            post,
	}
	mock.lockCreatePost.Lock()
	mock.calls.CreatePost = append(mock.calls.CreatePost, callInfo)
	mock.lockCreatePost.Unlock()
	return mock.CreatePostFunc(contextMoqParam, post)
}

// CreatePostCalls gets all the calls that were made to CreatePost.
// Check the length with:
//
//	len(mockedPostCommander.CreatePostCalls())
func (mock *PostCommanderMock) CreatePostCalls() []struct {
	ContextMoqParam context.Context
	Post            *domain.Post
} {
	var calls []struct {
		ContextMoqParam context.Context
		Post            *domain.Post
	}
	mock.lockCreatePost.RLock()
	calls = mock.calls.CreatePost
	mock.lockCreatePost.RUnlock()
	return calls
}

// DeletePost calls DeletePostFunc.
func (mock *PostCommanderMock) DeletePost(contextMoqParam context.Context, postID *domain.PostID) error {
	if mock.DeletePostFunc == nil {
		panic("PostCommanderMock.DeletePostFunc: method is nil but PostCommander.DeletePost was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		PostID          *domain.PostID
	}{
		ContextMoqParam: contextMoqParam,
		PostID:          postID,
	}
	mock.lockDeletePost.Lock()
	mock.calls.DeletePost = append(mock.calls.DeletePost, callInfo)
	mock.lockDeletePost.Unlock()
	return mock.DeletePostFunc(contextMoqParam, postID)
}

// DeletePostCalls gets all the calls that were made to DeletePost.
// Check the length with:
//
//	len(mockedPostCommander.DeletePostCalls())
func (mock *PostCommanderMock) DeletePostCalls() []struct {
	ContextMoqParam context.Context
	PostID          *domain.PostID
} {
	var calls []struct {
		ContextMoqParam context.Context
		PostID          *domain.PostID
	}
	mock.lockDeletePost.RLock()
	calls = mock.calls.DeletePost
	mock.lockDeletePost.RUnlock()
	return calls
}

// UpdatePost calls UpdatePostFunc.
func (mock *PostCommanderMock) UpdatePost(contextMoqParam context.Context, post *domain.Post) error {
	if mock.UpdatePostFunc == nil {
		panic("PostCommanderMock.UpdatePostFunc: method is nil but PostCommander.UpdatePost was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Post            *domain.Post
	}{
		ContextMoqParam: contextMoqParam,
		Post:            post,
	}
	mock.lockUpdatePost.Lock()
	mock.calls.UpdatePost = append(mock.calls.UpdatePost, callInfo)
	mock.lockUpdatePost.Unlock()
	return mock.UpdatePostFunc(contextMoqParam, post)
}

// UpdatePostCalls gets all the calls that were made to UpdatePost.
// Check the length with:
//
//	len(mockedPostCommander.UpdatePostCalls())
func (mock *PostCommanderMock) UpdatePostCalls() []struct {
	ContextMoqParam context.Context
	Post            *domain.Post
} {
	var calls []struct {
		ContextMoqParam context.Context
		Post            *domain.Post
	}
	mock.lockUpdatePost.RLock()
	calls = mock.calls.UpdatePost
	mock.lockUpdatePost.RUnlock()
	return calls
}
