// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package interfaces

import (
	"context"
	"github.com/becosuke/guestbook/api/internal/domain"
	"sync"
)

// Ensure, that PostQuerierMock does implement PostQuerier.
// If this is not the case, regenerate this file with moq.
var _ PostQuerier = &PostQuerierMock{}

// PostQuerierMock is a mock implementation of PostQuerier.
//
//	func TestSomethingThatUsesPostQuerier(t *testing.T) {
//
//		// make and configure a mocked PostQuerier
//		mockedPostQuerier := &PostQuerierMock{
//			GetPostFunc: func(contextMoqParam context.Context, postID *domain.PostID) (*domain.Post, error) {
//				panic("mock out the GetPost method")
//			},
//			RangePostsFunc: func(ctx context.Context, pageSize int32, cursor *domain.PostCursor) ([]*domain.Post, error) {
//				panic("mock out the RangePosts method")
//			},
//		}
//
//		// use mockedPostQuerier in code that requires PostQuerier
//		// and then make assertions.
//
//	}
type PostQuerierMock struct {
	// GetPostFunc mocks the GetPost method.
	GetPostFunc func(contextMoqParam context.Context, postID *domain.PostID) (*domain.Post, error)

	// RangePostsFunc mocks the RangePosts method.
	RangePostsFunc func(ctx context.Context, pageSize int32, cursor *domain.PostCursor) ([]*domain.Post, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetPost holds details about calls to the GetPost method.
		GetPost []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// PostID is the postID argument value.
			PostID *domain.PostID
		}
		// RangePosts holds details about calls to the RangePosts method.
		RangePosts []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PageSize is the pageSize argument value.
			PageSize int32
			// Cursor is the cursor argument value.
			Cursor *domain.PostCursor
		}
	}
	lockGetPost    sync.RWMutex
	lockRangePosts sync.RWMutex
}

// GetPost calls GetPostFunc.
func (mock *PostQuerierMock) GetPost(contextMoqParam context.Context, postID *domain.PostID) (*domain.Post, error) {
	if mock.GetPostFunc == nil {
		panic("PostQuerierMock.GetPostFunc: method is nil but PostQuerier.GetPost was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		PostID          *domain.PostID
	}{
		ContextMoqParam: contextMoqParam,
		PostID:          postID,
	}
	mock.lockGetPost.Lock()
	mock.calls.GetPost = append(mock.calls.GetPost, callInfo)
	mock.lockGetPost.Unlock()
	return mock.GetPostFunc(contextMoqParam, postID)
}

// GetPostCalls gets all the calls that were made to GetPost.
// Check the length with:
//
//	len(mockedPostQuerier.GetPostCalls())
func (mock *PostQuerierMock) GetPostCalls() []struct {
	ContextMoqParam context.Context
	PostID          *domain.PostID
} {
	var calls []struct {
		ContextMoqParam context.Context
		PostID          *domain.PostID
	}
	mock.lockGetPost.RLock()
	calls = mock.calls.GetPost
	mock.lockGetPost.RUnlock()
	return calls
}

// RangePosts calls RangePostsFunc.
func (mock *PostQuerierMock) RangePosts(ctx context.Context, pageSize int32, cursor *domain.PostCursor) ([]*domain.Post, error) {
	if mock.RangePostsFunc == nil {
		panic("PostQuerierMock.RangePostsFunc: method is nil but PostQuerier.RangePosts was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		PageSize int32
		Cursor   *domain.PostCursor
	}{
		Ctx:      ctx,
		PageSize: pageSize,
		Cursor:   cursor,
	}
	mock.lockRangePosts.Lock()
	mock.calls.RangePosts = append(mock.calls.RangePosts, callInfo)
	mock.lockRangePosts.Unlock()
	return mock.RangePostsFunc(ctx, pageSize, cursor)
}

// RangePostsCalls gets all the calls that were made to RangePosts.
// Check the length with:
//
//	len(mockedPostQuerier.RangePostsCalls())
func (mock *PostQuerierMock) RangePostsCalls() []struct {
	Ctx      context.Context
	PageSize int32
	Cursor   *domain.PostCursor
} {
	var calls []struct {
		Ctx      context.Context
		PageSize int32
		Cursor   *domain.PostCursor
	}
	mock.lockRangePosts.RLock()
	calls = mock.calls.RangePosts
	mock.lockRangePosts.RUnlock()
	return calls
}
