// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package interfaces

import (
	"context"
	"github.com/becosuke/guestbook/api/internal/domain"
	"sync"
)

// Ensure, that RepositoriesMock does implement Repositories.
// If this is not the case, regenerate this file with moq.
var _ Repositories = &RepositoriesMock{}

// RepositoriesMock is a mock implementation of Repositories.
//
//	func TestSomethingThatUsesRepositories(t *testing.T) {
//
//		// make and configure a mocked Repositories
//		mockedRepositories := &RepositoriesMock{
//			CreatePostFunc: func(contextMoqParam context.Context, post *domain.Post) error {
//				panic("mock out the CreatePost method")
//			},
//			DeletePostFunc: func(contextMoqParam context.Context, postID *domain.PostID) error {
//				panic("mock out the DeletePost method")
//			},
//			GetPaginationFunc: func(contextMoqParam context.Context, paginationID *domain.PaginationID) (*domain.Pagination, error) {
//				panic("mock out the GetPagination method")
//			},
//			GetPostFunc: func(contextMoqParam context.Context, postID *domain.PostID) (*domain.Post, error) {
//				panic("mock out the GetPost method")
//			},
//			RangePostsFunc: func(ctx context.Context, pageSize int32, cursor *domain.PostCursor) ([]*domain.Post, error) {
//				panic("mock out the RangePosts method")
//			},
//			SavePaginationFunc: func(contextMoqParam context.Context, pagination *domain.Pagination) error {
//				panic("mock out the SavePagination method")
//			},
//			UpdatePostFunc: func(contextMoqParam context.Context, post *domain.Post) error {
//				panic("mock out the UpdatePost method")
//			},
//		}
//
//		// use mockedRepositories in code that requires Repositories
//		// and then make assertions.
//
//	}
type RepositoriesMock struct {
	// CreatePostFunc mocks the CreatePost method.
	CreatePostFunc func(contextMoqParam context.Context, post *domain.Post) error

	// DeletePostFunc mocks the DeletePost method.
	DeletePostFunc func(contextMoqParam context.Context, postID *domain.PostID) error

	// GetPaginationFunc mocks the GetPagination method.
	GetPaginationFunc func(contextMoqParam context.Context, paginationID *domain.PaginationID) (*domain.Pagination, error)

	// GetPostFunc mocks the GetPost method.
	GetPostFunc func(contextMoqParam context.Context, postID *domain.PostID) (*domain.Post, error)

	// RangePostsFunc mocks the RangePosts method.
	RangePostsFunc func(ctx context.Context, pageSize int32, cursor *domain.PostCursor) ([]*domain.Post, error)

	// SavePaginationFunc mocks the SavePagination method.
	SavePaginationFunc func(contextMoqParam context.Context, pagination *domain.Pagination) error

	// UpdatePostFunc mocks the UpdatePost method.
	UpdatePostFunc func(contextMoqParam context.Context, post *domain.Post) error

	// calls tracks calls to the methods.
	calls struct {
		// CreatePost holds details about calls to the CreatePost method.
		CreatePost []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Post is the post argument value.
			Post *domain.Post
		}
		// DeletePost holds details about calls to the DeletePost method.
		DeletePost []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// PostID is the postID argument value.
			PostID *domain.PostID
		}
		// GetPagination holds details about calls to the GetPagination method.
		GetPagination []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// PaginationID is the paginationID argument value.
			PaginationID *domain.PaginationID
		}
		// GetPost holds details about calls to the GetPost method.
		GetPost []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// PostID is the postID argument value.
			PostID *domain.PostID
		}
		// RangePosts holds details about calls to the RangePosts method.
		RangePosts []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PageSize is the pageSize argument value.
			PageSize int32
			// Cursor is the cursor argument value.
			Cursor *domain.PostCursor
		}
		// SavePagination holds details about calls to the SavePagination method.
		SavePagination []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Pagination is the pagination argument value.
			Pagination *domain.Pagination
		}
		// UpdatePost holds details about calls to the UpdatePost method.
		UpdatePost []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Post is the post argument value.
			Post *domain.Post
		}
	}
	lockCreatePost     sync.RWMutex
	lockDeletePost     sync.RWMutex
	lockGetPagination  sync.RWMutex
	lockGetPost        sync.RWMutex
	lockRangePosts     sync.RWMutex
	lockSavePagination sync.RWMutex
	lockUpdatePost     sync.RWMutex
}

// CreatePost calls CreatePostFunc.
func (mock *RepositoriesMock) CreatePost(contextMoqParam context.Context, post *domain.Post) error {
	if mock.CreatePostFunc == nil {
		panic("RepositoriesMock.CreatePostFunc: method is nil but Repositories.CreatePost was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Post            *domain.Post
	}{
		ContextMoqParam: contextMoqParam,
		Post:            post,
	}
	mock.lockCreatePost.Lock()
	mock.calls.CreatePost = append(mock.calls.CreatePost, callInfo)
	mock.lockCreatePost.Unlock()
	return mock.CreatePostFunc(contextMoqParam, post)
}

// CreatePostCalls gets all the calls that were made to CreatePost.
// Check the length with:
//
//	len(mockedRepositories.CreatePostCalls())
func (mock *RepositoriesMock) CreatePostCalls() []struct {
	ContextMoqParam context.Context
	Post            *domain.Post
} {
	var calls []struct {
		ContextMoqParam context.Context
		Post            *domain.Post
	}
	mock.lockCreatePost.RLock()
	calls = mock.calls.CreatePost
	mock.lockCreatePost.RUnlock()
	return calls
}

// DeletePost calls DeletePostFunc.
func (mock *RepositoriesMock) DeletePost(contextMoqParam context.Context, postID *domain.PostID) error {
	if mock.DeletePostFunc == nil {
		panic("RepositoriesMock.DeletePostFunc: method is nil but Repositories.DeletePost was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		PostID          *domain.PostID
	}{
		ContextMoqParam: contextMoqParam,
		PostID:          postID,
	}
	mock.lockDeletePost.Lock()
	mock.calls.DeletePost = append(mock.calls.DeletePost, callInfo)
	mock.lockDeletePost.Unlock()
	return mock.DeletePostFunc(contextMoqParam, postID)
}

// DeletePostCalls gets all the calls that were made to DeletePost.
// Check the length with:
//
//	len(mockedRepositories.DeletePostCalls())
func (mock *RepositoriesMock) DeletePostCalls() []struct {
	ContextMoqParam context.Context
	PostID          *domain.PostID
} {
	var calls []struct {
		ContextMoqParam context.Context
		PostID          *domain.PostID
	}
	mock.lockDeletePost.RLock()
	calls = mock.calls.DeletePost
	mock.lockDeletePost.RUnlock()
	return calls
}

// GetPagination calls GetPaginationFunc.
func (mock *RepositoriesMock) GetPagination(contextMoqParam context.Context, paginationID *domain.PaginationID) (*domain.Pagination, error) {
	if mock.GetPaginationFunc == nil {
		panic("RepositoriesMock.GetPaginationFunc: method is nil but Repositories.GetPagination was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		PaginationID    *domain.PaginationID
	}{
		ContextMoqParam: contextMoqParam,
		PaginationID:    paginationID,
	}
	mock.lockGetPagination.Lock()
	mock.calls.GetPagination = append(mock.calls.GetPagination, callInfo)
	mock.lockGetPagination.Unlock()
	return mock.GetPaginationFunc(contextMoqParam, paginationID)
}

// GetPaginationCalls gets all the calls that were made to GetPagination.
// Check the length with:
//
//	len(mockedRepositories.GetPaginationCalls())
func (mock *RepositoriesMock) GetPaginationCalls() []struct {
	ContextMoqParam context.Context
	PaginationID    *domain.PaginationID
} {
	var calls []struct {
		ContextMoqParam context.Context
		PaginationID    *domain.PaginationID
	}
	mock.lockGetPagination.RLock()
	calls = mock.calls.GetPagination
	mock.lockGetPagination.RUnlock()
	return calls
}

// GetPost calls GetPostFunc.
func (mock *RepositoriesMock) GetPost(contextMoqParam context.Context, postID *domain.PostID) (*domain.Post, error) {
	if mock.GetPostFunc == nil {
		panic("RepositoriesMock.GetPostFunc: method is nil but Repositories.GetPost was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		PostID          *domain.PostID
	}{
		ContextMoqParam: contextMoqParam,
		PostID:          postID,
	}
	mock.lockGetPost.Lock()
	mock.calls.GetPost = append(mock.calls.GetPost, callInfo)
	mock.lockGetPost.Unlock()
	return mock.GetPostFunc(contextMoqParam, postID)
}

// GetPostCalls gets all the calls that were made to GetPost.
// Check the length with:
//
//	len(mockedRepositories.GetPostCalls())
func (mock *RepositoriesMock) GetPostCalls() []struct {
	ContextMoqParam context.Context
	PostID          *domain.PostID
} {
	var calls []struct {
		ContextMoqParam context.Context
		PostID          *domain.PostID
	}
	mock.lockGetPost.RLock()
	calls = mock.calls.GetPost
	mock.lockGetPost.RUnlock()
	return calls
}

// RangePosts calls RangePostsFunc.
func (mock *RepositoriesMock) RangePosts(ctx context.Context, pageSize int32, cursor *domain.PostCursor) ([]*domain.Post, error) {
	if mock.RangePostsFunc == nil {
		panic("RepositoriesMock.RangePostsFunc: method is nil but Repositories.RangePosts was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		PageSize int32
		Cursor   *domain.PostCursor
	}{
		Ctx:      ctx,
		PageSize: pageSize,
		Cursor:   cursor,
	}
	mock.lockRangePosts.Lock()
	mock.calls.RangePosts = append(mock.calls.RangePosts, callInfo)
	mock.lockRangePosts.Unlock()
	return mock.RangePostsFunc(ctx, pageSize, cursor)
}

// RangePostsCalls gets all the calls that were made to RangePosts.
// Check the length with:
//
//	len(mockedRepositories.RangePostsCalls())
func (mock *RepositoriesMock) RangePostsCalls() []struct {
	Ctx      context.Context
	PageSize int32
	Cursor   *domain.PostCursor
} {
	var calls []struct {
		Ctx      context.Context
		PageSize int32
		Cursor   *domain.PostCursor
	}
	mock.lockRangePosts.RLock()
	calls = mock.calls.RangePosts
	mock.lockRangePosts.RUnlock()
	return calls
}

// SavePagination calls SavePaginationFunc.
func (mock *RepositoriesMock) SavePagination(contextMoqParam context.Context, pagination *domain.Pagination) error {
	if mock.SavePaginationFunc == nil {
		panic("RepositoriesMock.SavePaginationFunc: method is nil but Repositories.SavePagination was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Pagination      *domain.Pagination
	}{
		ContextMoqParam: contextMoqParam,
		Pagination:      pagination,
	}
	mock.lockSavePagination.Lock()
	mock.calls.SavePagination = append(mock.calls.SavePagination, callInfo)
	mock.lockSavePagination.Unlock()
	return mock.SavePaginationFunc(contextMoqParam, pagination)
}

// SavePaginationCalls gets all the calls that were made to SavePagination.
// Check the length with:
//
//	len(mockedRepositories.SavePaginationCalls())
func (mock *RepositoriesMock) SavePaginationCalls() []struct {
	ContextMoqParam context.Context
	Pagination      *domain.Pagination
} {
	var calls []struct {
		ContextMoqParam context.Context
		Pagination      *domain.Pagination
	}
	mock.lockSavePagination.RLock()
	calls = mock.calls.SavePagination
	mock.lockSavePagination.RUnlock()
	return calls
}

// UpdatePost calls UpdatePostFunc.
func (mock *RepositoriesMock) UpdatePost(contextMoqParam context.Context, post *domain.Post) error {
	if mock.UpdatePostFunc == nil {
		panic("RepositoriesMock.UpdatePostFunc: method is nil but Repositories.UpdatePost was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Post            *domain.Post
	}{
		ContextMoqParam: contextMoqParam,
		Post:            post,
	}
	mock.lockUpdatePost.Lock()
	mock.calls.UpdatePost = append(mock.calls.UpdatePost, callInfo)
	mock.lockUpdatePost.Unlock()
	return mock.UpdatePostFunc(contextMoqParam, post)
}

// UpdatePostCalls gets all the calls that were made to UpdatePost.
// Check the length with:
//
//	len(mockedRepositories.UpdatePostCalls())
func (mock *RepositoriesMock) UpdatePostCalls() []struct {
	ContextMoqParam context.Context
	Post            *domain.Post
} {
	var calls []struct {
		ContextMoqParam context.Context
		Post            *domain.Post
	}
	mock.lockUpdatePost.RLock()
	calls = mock.calls.UpdatePost
	mock.lockUpdatePost.RUnlock()
	return calls
}
