CREATE TABLE IF NOT EXISTS Posts (
    PostId UUID PRIMARY KEY,
    PostBody VARCHAR(128) NOT NULL,
    CreateTime TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UpdateTime TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    DeleteTime TIMESTAMPTZ
);
