CREATE TABLE IF NOT EXISTS Posts (
    PostId UUID PRIMARY KEY,
    PostBody VARCHAR(128) NOT NULL,
    CreateTime TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UpdateTime TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    DeleteTime TIMESTAMPTZ NOT NULL DEFAULT '0001-01-01 00:00:00+00'
);

CREATE TABLE IF NOT EXISTS Paginations (
    PaginationId UUID PRIMARY KEY,
    Cursor JSONB NOT NULL,
    CreateTime TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
