// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repository

import (
	"context"
	"sync"

	domain "github.com/becosuke/guestbook/api/internal/domain/post"
)

// Ensure, that QuerierMock does implement Querier.
// If this is not the case, regenerate this file with moq.
var _ Querier = &QuerierMock{}

// QuerierMock is a mock implementation of Querier.
//
//	func TestSomethingThatUsesQuerier(t *testing.T) {
//
//		// make and configure a mocked Querier
//		mockedQuerier := &QuerierMock{
//			GetFunc: func(contextMoqParam context.Context, postID *domain.PostID) (*domain.Post, error) {
//				panic("mock out the Get method")
//			},
//			RangeFunc: func(contextMoqParam context.Context, pageOption *domain.PageOption) ([]*domain.Post, error) {
//				panic("mock out the Range method")
//			},
//		}
//
//		// use mockedQuerier in code that requires Querier
//		// and then make assertions.
//
//	}
type QuerierMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(contextMoqParam context.Context, postID *domain.PostID) (*domain.Post, error)

	// RangeFunc mocks the Range method.
	RangeFunc func(contextMoqParam context.Context, pageOption *domain.PageOption) ([]*domain.Post, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// PostID is the postID argument value.
			PostID *domain.PostID
		}
		// Range holds details about calls to the Range method.
		Range []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// PageOption is the pageOption argument value.
			PageOption *domain.PageOption
		}
	}
	lockGet   sync.RWMutex
	lockRange sync.RWMutex
}

// Get calls GetFunc.
func (mock *QuerierMock) Get(contextMoqParam context.Context, postID *domain.PostID) (*domain.Post, error) {
	if mock.GetFunc == nil {
		panic("QuerierMock.GetFunc: method is nil but Querier.Get was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		PostID          *domain.PostID
	}{
		ContextMoqParam: contextMoqParam,
		PostID:          postID,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(contextMoqParam, postID)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedQuerier.GetCalls())
func (mock *QuerierMock) GetCalls() []struct {
	ContextMoqParam context.Context
	PostID          *domain.PostID
} {
	var calls []struct {
		ContextMoqParam context.Context
		PostID          *domain.PostID
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Range calls RangeFunc.
func (mock *QuerierMock) Range(contextMoqParam context.Context, pageOption *domain.PageOption) ([]*domain.Post, error) {
	if mock.RangeFunc == nil {
		panic("QuerierMock.RangeFunc: method is nil but Querier.Range was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		PageOption      *domain.PageOption
	}{
		ContextMoqParam: contextMoqParam,
		PageOption:      pageOption,
	}
	mock.lockRange.Lock()
	mock.calls.Range = append(mock.calls.Range, callInfo)
	mock.lockRange.Unlock()
	return mock.RangeFunc(contextMoqParam, pageOption)
}

// RangeCalls gets all the calls that were made to Range.
// Check the length with:
//
//	len(mockedQuerier.RangeCalls())
func (mock *QuerierMock) RangeCalls() []struct {
	ContextMoqParam context.Context
	PageOption      *domain.PageOption
} {
	var calls []struct {
		ContextMoqParam context.Context
		PageOption      *domain.PageOption
	}
	mock.lockRange.RLock()
	calls = mock.calls.Range
	mock.lockRange.RUnlock()
	return calls
}
