// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"

	"go.uber.org/zap"

	"github.com/becosuke/guestbook/api/internal/pkg/config"
	"github.com/becosuke/guestbook/api/internal/pkg/logger"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context) *App {
	configConfig := config.NewConfig(ctx)
	zapLogger := logger.NewLogger(ctx, configConfig)
	app := &App{
		Config: configConfig,
		Logger: zapLogger,
	}
	return app
}

// wire.go:

type App struct {
	Config *config.Config
	Logger *zap.Logger
}
