// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=.ts"
// @generated from file guestbook.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "./google/api/annotations_pb.ts";
import { file_google_api_field_behavior } from "./google/api/field_behavior_pb.ts";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import { file_buf_validate_validate } from "./buf/validate/validate_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file guestbook.proto.
 */
export const file_guestbook: GenFile = /*@__PURE__*/
  fileDesc("Cg9ndWVzdGJvb2sucHJvdG8SAnBiIisKDkdldFBvc3RSZXF1ZXN0EhkKB3Bvc3RfaWQYASABKAlCCLpIBXIDsAEBIlYKEUNyZWF0ZVBvc3RSZXF1ZXN0Eh4KBHBvc3QYASABKAsyCC5wYi5Qb3N0Qga6SAPIAQESIQoPaWRlbXBvdGVuY3lfa2V5GAIgASgJQgi6SAVyA7ABASJWChFVcGRhdGVQb3N0UmVxdWVzdBIeCgRwb3N0GAEgASgLMggucGIuUG9zdEIGukgDyAEBEiEKD2lkZW1wb3RlbmN5X2tleRgCIAEoCUIIukgFcgOwAQEiUQoRRGVsZXRlUG9zdFJlcXVlc3QSGQoHcG9zdF9pZBgBIAEoCUIIukgFcgOwAQESIQoPaWRlbXBvdGVuY3lfa2V5GAIgASgJQgi6SAVyA7ABASJCChBMaXN0UG9zdHNSZXF1ZXN0EhoKCXBhZ2Vfc2l6ZRgBIAEoBUIHukgEGgIgABISCgpwYWdlX3Rva2VuGAIgASgJIkUKEUxpc3RQb3N0c1Jlc3BvbnNlEhcKBXBvc3RzGAEgAygLMggucGIuUG9zdBIXCg9uZXh0X3BhZ2VfdG9rZW4YAiABKAkiTwoEUG9zdBIZCgdwb3N0X2lkGAEgASgJQgi6SAVyA7ABARIYCgRib2R5GAIgASgJQgq6SAdyBRABGIABEhIKBXZhbGlkGAMgASgIQgPgQQMyxgMKEEd1ZXN0Ym9va1NlcnZpY2USRwoHR2V0UG9zdBISLnBiLkdldFBvc3RSZXF1ZXN0GggucGIuUG9zdCIegtPkkwIYEhYvYXBpL3YxL3Bvc3Qve3Bvc3RfaWR9EkYKCkNyZWF0ZVBvc3QSFS5wYi5DcmVhdGVQb3N0UmVxdWVzdBoILnBiLlBvc3QiF4LT5JMCEToBKiIML2FwaS92MS9wb3N0ElUKClVwZGF0ZVBvc3QSFS5wYi5VcGRhdGVQb3N0UmVxdWVzdBoILnBiLlBvc3QiJoLT5JMCIDoBKhobL2FwaS92MS9wb3N0L3twb3N0LnBvc3RfaWR9ElsKCkRlbGV0ZVBvc3QSFS5wYi5EZWxldGVQb3N0UmVxdWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSIegtPkkwIYKhYvYXBpL3YxL3Bvc3Qve3Bvc3RfaWR9Em0KCUxpc3RQb3N0cxIULnBiLkxpc3RQb3N0c1JlcXVlc3QaFS5wYi5MaXN0UG9zdHNSZXNwb25zZSIzgtPkkwItEisvYXBpL3YxL3Bvc3RzL2xpc3Qve3BhZ2Vfc2l6ZX0ve3BhZ2VfdG9rZW59Qi9aLWdpdGh1Yi5jb20vYmVjb3N1a2UvZ3Vlc3Rib29rL2ludGVybmFsL3BrZy9wYmIGcHJvdG8z", [file_google_api_annotations, file_google_api_field_behavior, file_google_protobuf_empty, file_buf_validate_validate]);

/**
 * @generated from message pb.GetPostRequest
 */
export type GetPostRequest = Message<"pb.GetPostRequest"> & {
  /**
   * @generated from field: string post_id = 1;
   */
  postId: string;
};

/**
 * Describes the message pb.GetPostRequest.
 * Use `create(GetPostRequestSchema)` to create a new message.
 */
export const GetPostRequestSchema: GenMessage<GetPostRequest> = /*@__PURE__*/
  messageDesc(file_guestbook, 0);

/**
 * @generated from message pb.CreatePostRequest
 */
export type CreatePostRequest = Message<"pb.CreatePostRequest"> & {
  /**
   * @generated from field: pb.Post post = 1;
   */
  post?: Post;

  /**
   * @generated from field: string idempotency_key = 2;
   */
  idempotencyKey: string;
};

/**
 * Describes the message pb.CreatePostRequest.
 * Use `create(CreatePostRequestSchema)` to create a new message.
 */
export const CreatePostRequestSchema: GenMessage<CreatePostRequest> = /*@__PURE__*/
  messageDesc(file_guestbook, 1);

/**
 * @generated from message pb.UpdatePostRequest
 */
export type UpdatePostRequest = Message<"pb.UpdatePostRequest"> & {
  /**
   * @generated from field: pb.Post post = 1;
   */
  post?: Post;

  /**
   * @generated from field: string idempotency_key = 2;
   */
  idempotencyKey: string;
};

/**
 * Describes the message pb.UpdatePostRequest.
 * Use `create(UpdatePostRequestSchema)` to create a new message.
 */
export const UpdatePostRequestSchema: GenMessage<UpdatePostRequest> = /*@__PURE__*/
  messageDesc(file_guestbook, 2);

/**
 * @generated from message pb.DeletePostRequest
 */
export type DeletePostRequest = Message<"pb.DeletePostRequest"> & {
  /**
   * @generated from field: string post_id = 1;
   */
  postId: string;

  /**
   * @generated from field: string idempotency_key = 2;
   */
  idempotencyKey: string;
};

/**
 * Describes the message pb.DeletePostRequest.
 * Use `create(DeletePostRequestSchema)` to create a new message.
 */
export const DeletePostRequestSchema: GenMessage<DeletePostRequest> = /*@__PURE__*/
  messageDesc(file_guestbook, 3);

/**
 * @generated from message pb.ListPostsRequest
 */
export type ListPostsRequest = Message<"pb.ListPostsRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message pb.ListPostsRequest.
 * Use `create(ListPostsRequestSchema)` to create a new message.
 */
export const ListPostsRequestSchema: GenMessage<ListPostsRequest> = /*@__PURE__*/
  messageDesc(file_guestbook, 4);

/**
 * @generated from message pb.ListPostsResponse
 */
export type ListPostsResponse = Message<"pb.ListPostsResponse"> & {
  /**
   * @generated from field: repeated pb.Post posts = 1;
   */
  posts: Post[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message pb.ListPostsResponse.
 * Use `create(ListPostsResponseSchema)` to create a new message.
 */
export const ListPostsResponseSchema: GenMessage<ListPostsResponse> = /*@__PURE__*/
  messageDesc(file_guestbook, 5);

/**
 * @generated from message pb.Post
 */
export type Post = Message<"pb.Post"> & {
  /**
   * @generated from field: string post_id = 1;
   */
  postId: string;

  /**
   * @generated from field: string body = 2;
   */
  body: string;

  /**
   * @generated from field: bool valid = 3;
   */
  valid: boolean;
};

/**
 * Describes the message pb.Post.
 * Use `create(PostSchema)` to create a new message.
 */
export const PostSchema: GenMessage<Post> = /*@__PURE__*/
  messageDesc(file_guestbook, 6);

/**
 * @generated from service pb.GuestbookService
 */
export const GuestbookService: GenService<{
  /**
   * @generated from rpc pb.GuestbookService.GetPost
   */
  getPost: {
    methodKind: "unary";
    input: typeof GetPostRequestSchema;
    output: typeof PostSchema;
  },
  /**
   * @generated from rpc pb.GuestbookService.CreatePost
   */
  createPost: {
    methodKind: "unary";
    input: typeof CreatePostRequestSchema;
    output: typeof PostSchema;
  },
  /**
   * @generated from rpc pb.GuestbookService.UpdatePost
   */
  updatePost: {
    methodKind: "unary";
    input: typeof UpdatePostRequestSchema;
    output: typeof PostSchema;
  },
  /**
   * @generated from rpc pb.GuestbookService.DeletePost
   */
  deletePost: {
    methodKind: "unary";
    input: typeof DeletePostRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc pb.GuestbookService.ListPosts
   */
  listPosts: {
    methodKind: "unary";
    input: typeof ListPostsRequestSchema;
    output: typeof ListPostsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_guestbook, 0);

