// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=.ts"
// @generated from file guestbook.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "./google/api/annotations_pb.ts";
import { file_google_api_field_behavior } from "./google/api/field_behavior_pb.ts";
import type { EmptySchema, Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_buf_validate_validate } from "./buf/validate/validate_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file guestbook.proto.
 */
export const file_guestbook: GenFile = /*@__PURE__*/
  fileDesc("Cg9ndWVzdGJvb2sucHJvdG8SAnBiIisKDkdldFBvc3RSZXF1ZXN0EhkKB3Bvc3RfaWQYASABKAlCCLpIBXIDsAEBIlYKEUNyZWF0ZVBvc3RSZXF1ZXN0Eh4KBHBvc3QYASABKAsyCC5wYi5Qb3N0Qga6SAPIAQESIQoPaWRlbXBvdGVuY3lfa2V5GAIgASgJQgi6SAVyA7ABASK7AQoRVXBkYXRlUG9zdFJlcXVlc3QSHgoEcG9zdBgBIAEoCzIILnBiLlBvc3RCBrpIA8gBARIhCg9pZGVtcG90ZW5jeV9rZXkYAiABKAlCCLpIBXIDsAEBOmO6SGAaXgopdXBkYXRlX3Bvc3RfcmVxdWVzdC5wb3N0LnBvc3RfaWRfcmVxdWlyZWQSGHBvc3QucG9zdF9pZCBpcyByZXF1aXJlZBoXdGhpcy5wb3N0LnBvc3RfaWQgIT0gJyciUQoRRGVsZXRlUG9zdFJlcXVlc3QSGQoHcG9zdF9pZBgBIAEoCUIIukgFcgOwAQESIQoPaWRlbXBvdGVuY3lfa2V5GAIgASgJQgi6SAVyA7ABASJCChBMaXN0UG9zdHNSZXF1ZXN0EhoKCXBhZ2Vfc2l6ZRgBIAEoBUIHukgEGgIgABISCgpwYWdlX3Rva2VuGAIgASgJIkUKEUxpc3RQb3N0c1Jlc3BvbnNlEhcKBXBvc3RzGAEgAygLMggucGIuUG9zdBIXCg9uZXh0X3BhZ2VfdG9rZW4YAiABKAki2gEKBFBvc3QSHAoHcG9zdF9pZBgBIAEoCUILukgI2AEBcgOwAQESGAoEYm9keRgCIAEoCUIKukgHcgUQARiAARISCgV2YWxpZBgDIAEoCEID4EEDEjQKC2NyZWF0ZV90aW1lGAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEID4EEDEjQKC3VwZGF0ZV90aW1lGAUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEID4EEDEhoKDXByZXZpb3VzX2JvZHkYBiABKAlCA+BBAzLGAwoQR3Vlc3Rib29rU2VydmljZRJHCgdHZXRQb3N0EhIucGIuR2V0UG9zdFJlcXVlc3QaCC5wYi5Qb3N0Ih6C0+STAhgSFi9hcGkvdjEvcG9zdC97cG9zdF9pZH0SRgoKQ3JlYXRlUG9zdBIVLnBiLkNyZWF0ZVBvc3RSZXF1ZXN0GggucGIuUG9zdCIXgtPkkwIROgEqIgwvYXBpL3YxL3Bvc3QSVQoKVXBkYXRlUG9zdBIVLnBiLlVwZGF0ZVBvc3RSZXF1ZXN0GggucGIuUG9zdCImgtPkkwIgOgEqGhsvYXBpL3YxL3Bvc3Qve3Bvc3QucG9zdF9pZH0SWwoKRGVsZXRlUG9zdBIVLnBiLkRlbGV0ZVBvc3RSZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5Ih6C0+STAhgqFi9hcGkvdjEvcG9zdC97cG9zdF9pZH0SbQoJTGlzdFBvc3RzEhQucGIuTGlzdFBvc3RzUmVxdWVzdBoVLnBiLkxpc3RQb3N0c1Jlc3BvbnNlIjOC0+STAi0SKy9hcGkvdjEvcG9zdHMvbGlzdC97cGFnZV9zaXplfS97cGFnZV90b2tlbn1CL1otZ2l0aHViLmNvbS9iZWNvc3VrZS9ndWVzdGJvb2svaW50ZXJuYWwvcGtnL3BiYgZwcm90bzM", [file_google_api_annotations, file_google_api_field_behavior, file_google_protobuf_empty, file_google_protobuf_timestamp, file_buf_validate_validate]);

/**
 * @generated from message pb.GetPostRequest
 */
export type GetPostRequest = Message<"pb.GetPostRequest"> & {
  /**
   * @generated from field: string post_id = 1;
   */
  postId: string;
};

/**
 * Describes the message pb.GetPostRequest.
 * Use `create(GetPostRequestSchema)` to create a new message.
 */
export const GetPostRequestSchema: GenMessage<GetPostRequest> = /*@__PURE__*/
  messageDesc(file_guestbook, 0);

/**
 * @generated from message pb.CreatePostRequest
 */
export type CreatePostRequest = Message<"pb.CreatePostRequest"> & {
  /**
   * @generated from field: pb.Post post = 1;
   */
  post?: Post;

  /**
   * @generated from field: string idempotency_key = 2;
   */
  idempotencyKey: string;
};

/**
 * Describes the message pb.CreatePostRequest.
 * Use `create(CreatePostRequestSchema)` to create a new message.
 */
export const CreatePostRequestSchema: GenMessage<CreatePostRequest> = /*@__PURE__*/
  messageDesc(file_guestbook, 1);

/**
 * @generated from message pb.UpdatePostRequest
 */
export type UpdatePostRequest = Message<"pb.UpdatePostRequest"> & {
  /**
   * @generated from field: pb.Post post = 1;
   */
  post?: Post;

  /**
   * @generated from field: string idempotency_key = 2;
   */
  idempotencyKey: string;
};

/**
 * Describes the message pb.UpdatePostRequest.
 * Use `create(UpdatePostRequestSchema)` to create a new message.
 */
export const UpdatePostRequestSchema: GenMessage<UpdatePostRequest> = /*@__PURE__*/
  messageDesc(file_guestbook, 2);

/**
 * @generated from message pb.DeletePostRequest
 */
export type DeletePostRequest = Message<"pb.DeletePostRequest"> & {
  /**
   * @generated from field: string post_id = 1;
   */
  postId: string;

  /**
   * @generated from field: string idempotency_key = 2;
   */
  idempotencyKey: string;
};

/**
 * Describes the message pb.DeletePostRequest.
 * Use `create(DeletePostRequestSchema)` to create a new message.
 */
export const DeletePostRequestSchema: GenMessage<DeletePostRequest> = /*@__PURE__*/
  messageDesc(file_guestbook, 3);

/**
 * @generated from message pb.ListPostsRequest
 */
export type ListPostsRequest = Message<"pb.ListPostsRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message pb.ListPostsRequest.
 * Use `create(ListPostsRequestSchema)` to create a new message.
 */
export const ListPostsRequestSchema: GenMessage<ListPostsRequest> = /*@__PURE__*/
  messageDesc(file_guestbook, 4);

/**
 * @generated from message pb.ListPostsResponse
 */
export type ListPostsResponse = Message<"pb.ListPostsResponse"> & {
  /**
   * @generated from field: repeated pb.Post posts = 1;
   */
  posts: Post[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message pb.ListPostsResponse.
 * Use `create(ListPostsResponseSchema)` to create a new message.
 */
export const ListPostsResponseSchema: GenMessage<ListPostsResponse> = /*@__PURE__*/
  messageDesc(file_guestbook, 5);

/**
 * @generated from message pb.Post
 */
export type Post = Message<"pb.Post"> & {
  /**
   * @generated from field: string post_id = 1;
   */
  postId: string;

  /**
   * @generated from field: string body = 2;
   */
  body: string;

  /**
   * @generated from field: bool valid = 3;
   */
  valid: boolean;

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 4;
   */
  createTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp update_time = 5;
   */
  updateTime?: Timestamp;

  /**
   * @generated from field: string previous_body = 6;
   */
  previousBody: string;
};

/**
 * Describes the message pb.Post.
 * Use `create(PostSchema)` to create a new message.
 */
export const PostSchema: GenMessage<Post> = /*@__PURE__*/
  messageDesc(file_guestbook, 6);

/**
 * @generated from service pb.GuestbookService
 */
export const GuestbookService: GenService<{
  /**
   * @generated from rpc pb.GuestbookService.GetPost
   */
  getPost: {
    methodKind: "unary";
    input: typeof GetPostRequestSchema;
    output: typeof PostSchema;
  },
  /**
   * @generated from rpc pb.GuestbookService.CreatePost
   */
  createPost: {
    methodKind: "unary";
    input: typeof CreatePostRequestSchema;
    output: typeof PostSchema;
  },
  /**
   * @generated from rpc pb.GuestbookService.UpdatePost
   */
  updatePost: {
    methodKind: "unary";
    input: typeof UpdatePostRequestSchema;
    output: typeof PostSchema;
  },
  /**
   * @generated from rpc pb.GuestbookService.DeletePost
   */
  deletePost: {
    methodKind: "unary";
    input: typeof DeletePostRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc pb.GuestbookService.ListPosts
   */
  listPosts: {
    methodKind: "unary";
    input: typeof ListPostsRequestSchema;
    output: typeof ListPostsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_guestbook, 0);

