CREATE TABLE IF NOT EXISTS posts (
    PostId UUID PRIMARY KEY,
    Body VARCHAR(128) NOT NULL,
    CreateTime TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UpdateTime TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
