CREATE TABLE IF NOT EXISTS posts (
    post_id UUID PRIMARY KEY,
    body VARCHAR(128) NOT NULL,
    create_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    update_time TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
