CREATE TABLE IF NOT EXISTS posts (
    post_id UUID PRIMARY KEY,
    body VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
